### ISSUE TITLE
Item Wheel not working

### ISSUE THREAD

**Issue by Lenni0451** [DarkFlare69/MK7-NTR-Plugin#1]
I'm using this Plugin on an EUR New 3Ds with EUR Mk7 Rev1

The Item Wheel code is not working for me in offline Mode. I Don't know if its working online

**Comment by DarkFlare69** [comment]
Try the Rev0 code.

**Comment by DarkFlare69** [comment]
Just updated and it should work now. Open a new issue if it still doesn't
