### ISSUE TITLE
Doesnt flash green????

### ISSUE THREAD

**Issue by MrHaqs** [DarkFlare69/MK7-NTR-Plugin#2]
I boot NTR 3.4
Start the game
Doesnt flash green
Menu pops up
Cheat menu doesnt

On 11.2 o3ds mk7 usa rev0

**Comment by DarkFlare69** [comment]
Is the plugin in sd:/plugin/(title id for your region)/MarioKart7.plg  ?

Did you set up a custom plugin path?

**Comment by MrHaqs** [comment]
Nvm its sorted
